# Generated by Django 4.0.4 on 2023-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_course_user_mcquestion_course_standard_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='standards',
            field=models.ManyToManyField(to='dashboard.standard'),
        ),
    ]
