# Generated by Django 4.0.4 on 2023-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mcquestion_standards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcoption',
            name='mcquestion',
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='choices',
            field=models.ManyToManyField(to='dashboard.mcoption'),
        ),
    ]
